os: linux
language: node_js
node_js:
  - "10"
script:
  npm run build
env:
  global:
    - secure: rKjqhJ+CTIr0MXVuyCUPhBS4nR5vhrnICFsp1skNvrVBVlgB18QXI2+ICPDbMYgJ5VCaDdI+chc8eFVvfOSXcvJHk80f/kPKeSfO/ivMNBgZKBQBx8t6xuQlh0MZ8jZ/dTQky4dxPA5EOBPBSu3X1vxdpzIiHzXs2DqCY1J/Hqn1DJ908It2X9niLWBFoGOPRKLVSyjllMOQDG+i2H3IFY8GWRC+sR8/b8shjgfaFHGjzLN33cJjTWjsnNv4AUKsT2u9d39YG8RyuTVDqHfhcOXOznylONm8gb9oKWAHxqMWkUMA4c5Kn4BmAiS4HxohnX74K9ggKJlAAkY0K8/IN+PTXylmH4TQkzWNv9rKNAaWnvgA2J4agyROo+Qby49a9U+3XhnRECpGMfy7LTL8vboEDKXqgqhBMI5RalhMH7vOSHx/U87JSNgNTIGkXykhTszAqmYF1Dt/wWsaW4zV2STMEexeufBYEPcBCHXI82A6F4BDi+m4Zh8D4Neg7sUGkQzT/FFHIupLRBIgiulgz9VRQ2nZ8kmQbCmh0Qs49keDHd9Pgxk2HENwdkjWm5/vSHAFQ08tBcbltUVjrIpMTy43l3szvWSTqsrBrL56neKo1ttu/eSebMEJ8Mt7tX+gRiltk3SMWm4hi514s8/Dl3QF9HvHEiheuYOp3eJI6AI=
deploy:
  provider: pages
  skip-cleanup: true
  github-token: env.global[0].secure
  keep-history: true
  local-dir: public
  on:
    branch: master
